import type { Student } from "./student";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "1",
    firstName: "Aarav",
    lastName: "Sharma",
    dateOfBirth: "2010-04-15",
    gender: "male",
    bloodGroup: "B+",
    nationality: "Nepali",
    religion: "Hindu",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav&backgroundColor=b6e3f4",
    status: "active",
    studentId: "STU-2024-001",
    grade: "Grade 8",
    section: "A",
    rollNumber: "01",
    admissionDate: "2020-04-01",
    previousSchool: "Sunrise Academy",
    gpa: 3.8,
    email: "aarav.sharma@student.edu",
    phone: "+977-9841234567",
    address: "123 Thamel Street",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    parentName: "Ramesh Sharma",
    parentPhone: "+977-9841111111",
    parentEmail: "ramesh.sharma@email.com",
    parentOccupation: "Engineer",
    medicalConditions: "None",
    allergies: "None",
    subjectProgress: [
      { subject: "Mathematics", score: 94, grade: "A+", attendance: 98 },
      { subject: "Science", score: 88, grade: "A", attendance: 95 },
      { subject: "English", score: 82, grade: "A-", attendance: 100 },
      { subject: "Social Studies", score: 78, grade: "B+", attendance: 92 },
      { subject: "Nepali", score: 91, grade: "A+", attendance: 97 },
    ],
    attendanceHistory: [
      { month: "Jan", present: 22, absent: 0, total: 22 },
      { month: "Feb", present: 19, absent: 1, total: 20 },
      { month: "Mar", present: 23, absent: 0, total: 23 },
      { month: "Apr", present: 20, absent: 2, total: 22 },
      { month: "May", present: 21, absent: 1, total: 22 },
      { month: "Jun", present: 18, absent: 0, total: 18 },
    ],
    achievements: [
      { title: "Math Olympiad – 1st Place", date: "2024-03-10", category: "academic" },
      { title: "Science Fair Winner", date: "2024-01-20", category: "academic" },
      { title: "Football Team Captain", date: "2023-11-05", category: "sports" },
    ],
    transportMode: "school_bus",
    extracurriculars: ["Football", "Chess", "Science Club"],
  },
  {
    id: "2",
    firstName: "Priya",
    lastName: "Thapa",
    dateOfBirth: "2011-08-22",
    gender: "female",
    bloodGroup: "O+",
    nationality: "Nepali",
    religion: "Hindu",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya&backgroundColor=ffd5dc",
    status: "active",
    studentId: "STU-2024-002",
    grade: "Grade 7",
    section: "B",
    rollNumber: "07",
    admissionDate: "2021-04-01",
    gpa: 3.6,
    email: "priya.thapa@student.edu",
    phone: "+977-9852345678",
    address: "45 Lazimpat Road",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    parentName: "Sunita Thapa",
    parentPhone: "+977-9852222222",
    parentOccupation: "Doctor",
    subjectProgress: [
      { subject: "Mathematics", score: 78, grade: "B+", attendance: 96 },
      { subject: "Science", score: 92, grade: "A+", attendance: 98 },
      { subject: "English", score: 89, grade: "A", attendance: 100 },
      { subject: "Social Studies", score: 85, grade: "A-", attendance: 94 },
      { subject: "Nepali", score: 76, grade: "B+", attendance: 96 },
    ],
    attendanceHistory: [
      { month: "Jan", present: 21, absent: 1, total: 22 },
      { month: "Feb", present: 20, absent: 0, total: 20 },
      { month: "Mar", present: 22, absent: 1, total: 23 },
      { month: "Apr", present: 22, absent: 0, total: 22 },
      { month: "May", present: 20, absent: 2, total: 22 },
      { month: "Jun", present: 17, absent: 1, total: 18 },
    ],
    achievements: [
      { title: "Best Science Project", date: "2024-02-14", category: "academic" },
      { title: "Dance Competition – 2nd Place", date: "2023-12-10", category: "arts" },
    ],
    transportMode: "private",
    extracurriculars: ["Dance", "Science Club", "Debate Club"],
  },
  {
    id: "3",
    firstName: "Bikash",
    lastName: "Gurung",
    dateOfBirth: "2009-12-05",
    gender: "male",
    bloodGroup: "A+",
    nationality: "Nepali",
    religion: "Buddhist",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bikash&backgroundColor=c0aede",
    status: "active",
    studentId: "STU-2024-003",
    grade: "Grade 9",
    section: "C",
    rollNumber: "12",
    admissionDate: "2019-04-01",
    previousSchool: "Mountain View School",
    gpa: 3.2,
    phone: "+977-9863456789",
    address: "78 Baneshwor, Ward 10",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    parentName: "Dil Bahadur Gurung",
    parentPhone: "+977-9863333333",
    parentOccupation: "Business",
    allergies: "Dust",
    subjectProgress: [
      { subject: "Mathematics", score: 72, grade: "B", attendance: 88 },
      { subject: "Science", score: 80, grade: "B+", attendance: 90 },
      { subject: "English", score: 68, grade: "B-", attendance: 85 },
      { subject: "Social Studies", score: 75, grade: "B", attendance: 91 },
      { subject: "Nepali", score: 82, grade: "A-", attendance: 94 },
    ],
    attendanceHistory: [
      { month: "Jan", present: 19, absent: 3, total: 22 },
      { month: "Feb", present: 17, absent: 3, total: 20 },
      { month: "Mar", present: 21, absent: 2, total: 23 },
      { month: "Apr", present: 18, absent: 4, total: 22 },
      { month: "May", present: 19, absent: 3, total: 22 },
      { month: "Jun", present: 15, absent: 3, total: 18 },
    ],
    achievements: [
      { title: "Basketball Championship", date: "2024-01-30", category: "sports" },
    ],
    transportMode: "walking",
    extracurriculars: ["Basketball", "Photography"],
  },
  {
    id: "4",
    firstName: "Sarita",
    lastName: "Rai",
    dateOfBirth: "2010-06-18",
    gender: "female",
    bloodGroup: "AB+",
    nationality: "Nepali",
    religion: "Hindu",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarita&backgroundColor=d1f7c4",
    status: "inactive",
    studentId: "STU-2024-004",
    grade: "Grade 8",
    section: "A",
    rollNumber: "18",
    admissionDate: "2020-04-01",
    gpa: 2.9,
    email: "sarita.rai@student.edu",
    phone: "+977-9874567890",
    address: "56 Patan Durbar Marg",
    city: "Lalitpur",
    state: "Bagmati",
    country: "Nepal",
    parentName: "Manisha Rai",
    parentPhone: "+977-9874444444",
    parentEmail: "manisha.rai@email.com",
    medicalConditions: "Mild Asthma",
    allergies: "Pollen",
    subjectProgress: [
      { subject: "Mathematics", score: 65, grade: "C+", attendance: 80 },
      { subject: "Science", score: 70, grade: "B-", attendance: 82 },
      { subject: "English", score: 74, grade: "B", attendance: 85 },
      { subject: "Social Studies", score: 68, grade: "B-", attendance: 78 },
      { subject: "Nepali", score: 72, grade: "B", attendance: 83 },
    ],
    attendanceHistory: [
      { month: "Jan", present: 18, absent: 4, total: 22 },
      { month: "Feb", present: 16, absent: 4, total: 20 },
      { month: "Mar", present: 19, absent: 4, total: 23 },
      { month: "Apr", present: 17, absent: 5, total: 22 },
      { month: "May", present: 18, absent: 4, total: 22 },
      { month: "Jun", present: 14, absent: 4, total: 18 },
    ],
    achievements: [],
    transportMode: "school_bus",
    extracurriculars: ["Art & Craft"],
  },
  {
    id: "5",
    firstName: "Rohan",
    lastName: "Basnet",
    dateOfBirth: "2008-03-30",
    gender: "male",
    bloodGroup: "B-",
    nationality: "Nepali",
    religion: "Hindu",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan&backgroundColor=ffdfbf",
    status: "active",
    studentId: "STU-2024-005",
    grade: "Grade 10",
    section: "D",
    rollNumber: "05",
    admissionDate: "2018-04-01",
    previousSchool: "Valley School",
    gpa: 3.9,
    email: "rohan.basnet@student.edu",
    phone: "+977-9885678901",
    address: "22 Chabahil, Ward 7",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    parentName: "Gopal Basnet",
    parentPhone: "+977-9885555555",
    parentEmail: "gopal.basnet@email.com",
    parentOccupation: "Professor",
    subjectProgress: [
      { subject: "Mathematics", score: 97, grade: "A+", attendance: 100 },
      { subject: "Science", score: 95, grade: "A+", attendance: 99 },
      { subject: "English", score: 91, grade: "A+", attendance: 100 },
      { subject: "Social Studies", score: 88, grade: "A", attendance: 98 },
      { subject: "Nepali", score: 93, grade: "A+", attendance: 99 },
    ],
    attendanceHistory: [
      { month: "Jan", present: 22, absent: 0, total: 22 },
      { month: "Feb", present: 20, absent: 0, total: 20 },
      { month: "Mar", present: 23, absent: 0, total: 23 },
      { month: "Apr", present: 22, absent: 0, total: 22 },
      { month: "May", present: 22, absent: 0, total: 22 },
      { month: "Jun", present: 18, absent: 0, total: 18 },
    ],
    achievements: [
      { title: "National Science Olympiad – Gold", date: "2024-03-20", category: "academic" },
      { title: "Class Topper 2023-24", date: "2024-04-01", category: "academic" },
      { title: "Debate Championship Winner", date: "2024-02-05", category: "leadership" },
    ],
    transportMode: "private",
    extracurriculars: ["Debate Club", "Coding Club", "Math Olympiad", "Music"],
  },
  {
    id: "6",
    firstName: "Anita",
    lastName: "Karki",
    dateOfBirth: "2011-11-09",
    gender: "female",
    bloodGroup: "O-",
    nationality: "Nepali",
    religion: "Hindu",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anita&backgroundColor=ffeaa7",
    status: "transferred",
    studentId: "STU-2024-006",
    grade: "Grade 7",
    section: "A",
    rollNumber: "23",
    admissionDate: "2021-04-01",
    gpa: 3.1,
    phone: "+977-9896789012",
    address: "34 Bhaktapur Durbar",
    city: "Bhaktapur",
    state: "Bagmati",
    country: "Nepal",
    parentName: "Binod Karki",
    parentPhone: "+977-9896666666",
    subjectProgress: [
      { subject: "Mathematics", score: 75, grade: "B", attendance: 90 },
      { subject: "Science", score: 78, grade: "B+", attendance: 92 },
      { subject: "English", score: 80, grade: "B+", attendance: 94 },
      { subject: "Social Studies", score: 72, grade: "B", attendance: 88 },
      { subject: "Nepali", score: 84, grade: "A-", attendance: 95 },
    ],
    attendanceHistory: [
      { month: "Jan", present: 20, absent: 2, total: 22 },
      { month: "Feb", present: 18, absent: 2, total: 20 },
      { month: "Mar", present: 21, absent: 2, total: 23 },
      { month: "Apr", present: 19, absent: 3, total: 22 },
      { month: "May", present: 20, absent: 2, total: 22 },
      { month: "Jun", present: 16, absent: 2, total: 18 },
    ],
    achievements: [
      { title: "Art Exhibition – Best Painting", date: "2023-10-15", category: "arts" },
    ],
    transportMode: "school_bus",
    extracurriculars: ["Art & Craft", "Swimming"],
  },
];
